name: build-check

on: [push]

jobs:
  ubuntu:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get Vulkan Version
      run: |
        SDK_VERSION=`curl https://vulkan.lunarg.com/sdk/latest/linux.txt`
        echo "SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV

    - name: Create build cache 
      uses: actions/cache@v3
      id: build-cache
      with:
        path: |
          vulkan/
          build/
        key: ${{ runner.OS }}-${{ env.SDK_VERSION }}

    - name: Install Vulkan SDK
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: |
        curl -O https://sdk.lunarg.com/sdk/download/${SDK_VERSION}/linux/vulkan_sdk.tar.gz
        mkdir -p vulkan/
        tar -xzvf vulkan_sdk.tar.gz -C vulkan/

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y xorg-dev

    - name: Configure CMake cache
      run: |
        source vulkan/${SDK_VERSION}/setup-env.sh
        mkdir -p build
        cd build
        rm -f CMakeCache.txt
        cmake .. -DBUILD_TESTS=ON

    - name: Build
      run: |
        cd build
        cmake --build . --target kronic kronic_tests --config Debug -j2

    - name: Test
      run: ./build/bin/kronic_tests

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kronic-ubuntu-${{ github.sha }}
        if-no-files-found: error
        path: |
          ./build/bin/kronic

  windows:
    runs-on: "windows-latest"
    env:
      VULKAN_SDK: C:\VulkanSDK\

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get Vulkan Version
      run: |
        $env:SDK_VERSION = (curl https://vulkan.lunarg.com/sdk/latest/windows.txt)
        echo "SDK_VERSION=$env:SDK_VERSION" >> $env:GITHUB_ENV

    - name: Create build cache 
      uses: actions/cache@v3
      id: build-cache
      with:
        path: |
          vulkan/
          build/
        key: ${{ runner.OS }}-${{ env.SDK_VERSION }}

    - name: Install Vulkan SDK
      run: |
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
          echo Version $ver
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
          echo Downloaded
          $location = -join((Get-Location), "/vulkan")
          .\VulkanSDK.exe --root $location --accept-licenses --default-answer --confirm-command install

    - name: Configure CMake cache
      run: |
        test -d build || mkdir build
        cd build
        rm CMakeCache.txt -ErrorAction Ignore
        cmake .. -DBUILD_TESTS=ON

    # TODO: Fix this.
    # We do a release build because the LunarG Vulkan SDK ships 
    # with a shaderc_combined.lib that links to release mode 
    # multithreaded runtime binaries. Doing a debug build with 
    # it would lead to linking errors.
    - name: Build
      run: |
        cd build
        cmake --build . --target kronic kronic_tests --config Release -j2

    - name: Test
      run: ./build/bin/Release/kronic_tests.exe

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kronic-windows-${{ github.sha }}
        if-no-files-found: error
        path: |
          ./build/bin/Release/kronic.exe
