name: build-check

on: [push]

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: install dependencies
      run: sudo apt install vulkan-tools libvulkan-dev libglfw3-dev

    - name: configure
      run: mkdir build && cd build && cmake .. -DBUILD_TESTS=ON

    - name: build
      run: cd build && cmake --build . --config Debug

    - name: test
      run: ./build/tests/kronic_tests
