name: build-check

on: [push]

jobs:
  ubuntu:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Monolithic Vulkan SDK binary release
      uses: humbletim/setup-vulkan-sdk@main
      with:
        vulkan-version: 1.3.204.0
        vulkan-components: prebuilt

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y xorg-dev

    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_TESTS=ON

    - name: build
      run: |
        cd build
        cmake --build . --config Debug -j2

    - name: test
      run: ./build/tests/kronic_tests

    - uses: actions/upload-artifact@v2
      with:
        name: kronic-ubuntu-${{ github.sha }}
        if-no-files-found: error
        path: |
          ./build/kronic/kronic

  windows:
    runs-on: "windows-latest"
    env:
      VULKAN_SDK: C:\VulkanSDK\

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: setup Vulkan
      run: |
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
          echo Version $ver
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
          echo Downloaded
          .\VulkanSDK.exe --root C:\VulkanSDK  --accept-licenses --default-answer --confirm-command install

    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_TESTS=ON

    - name: build
      run: |
        cd build
        cmake --build . --config Debug -j2

    - name: test
      run: ./build/tests/Debug/kronic_tests

    - uses: actions/upload-artifact@v2
      with:
        name: kronic-windows-${{ github.sha }}
        if-no-files-found: error
        path: |
          ./build/kronic/Debug/kronic.exe
